name: etona
description: A mobile game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  audioplayers: ^1.0.1
  cloud_firestore:
  cloud_functions:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  flutter_hooks:
  flutter_svg:
  freezed_annotation:
  go_router: ^4.4.1
  hooks_riverpod:
  image_picker:
  json_annotation:
  logging: ^1.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  firebase_auth:
  firebase_core: ^1.15.0  # Needed for Crashlytics below
  firebase_crashlytics: ^2.8.1  # Error reporting
  games_services: ^3.0.0  # Achievements and leaderboards
  google_mobile_ads: ^2.0.1  # Ads
  in_app_purchase: ^3.0.1  # In-app purchases

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  freezed:
  json_serializable:
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/icons/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: NotoSansJp
      fonts:
        - asset: assets/noto_sans_jp/NotoSansJP-Thin.otf
          weight: 100
        - asset: assets/noto_sans_jp/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/noto_sans_jp/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/noto_sans_jp/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/noto_sans_jp/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/noto_sans_jp/NotoSansJP-Black.otf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
